### PR TITLE
fix crash while dynamically delete rows from tableview with animation

### PR DESCRIPTION
**Pull request by astrokin**

### CODE REVIEW

**Comment by maxsokolov** [comment]
Hi @astrokin 

I see that you are using method
```indices.contains(index)```

I think this is not good for performance reasons. The cost of this operation is O(n) in worst case, and this is going to be called a lot because method `invoke` is calling for many delegate/datasource method for UITableView.

**Comment by astrokin** [comment]
Hi @maxsokolov afaik NO :) 

> Complexity: O(1) if the collection conforms to RandomAccessCollection; otherwise, O(n), where n is the length of the collection.

> public struct Array<Element> : RandomAccessCollection, MutableCollection

[developer.apple.com](https://developer.apple.com/documentation/swift/countablerange/2949699-count?changes=latest_5__2)

**Comment by maxsokolov** [comment]
@astrokin 

the link above is pointing to `count` property.

**Comment by maxsokolov** [comment]
But I may be wrong about O(n). I see that `indices` is CountableRange, not an Array.

**Comment by astrokin** [comment]
@maxsokolov my fault. seems miss-reading... i'll add my case in demo project later to demonstrate the case. Please feel free to close this PR

**Comment by maxsokolov** [comment]
@astrokin I've added simple check [here](https://github.com/maxsokolov/TableKit/pull/79/files#diff-4c620128de469028e8e007366e658838R100).
Thanks for pointing out to the problem!

**Pull request closed without merging**
